spring.application.name=employee-services
server.port=8086
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_master
spring.datasource.username=postgres
spring.datasource.password=abc123def
spring.jpa.show.sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update